exports.up = async function (knex) {
    return await knex('attractions').insert([
        { attraction_id: 'a001', attraction_name: 'Vịnh Hạ Long', description: 'Vịnh Hạ Long là một trong những kỳ quan thiên nhiên của thế giới, nổi tiếng với những đảo đá vôi kỳ lạ và phong cảnh tuyệt đẹp.', location_id: 'l004', contact: '024 3878 9572', opening_hours: '08:00-17:00', rating: 4.6, img_url: 'https://i.imgur.com/ccr0t0c.jpg' },
        { attraction_id: 'a002', attraction_name: 'Thác Bản Giốc', description: 'Thác Bản Giốc là một trong những thác nước đẹp nhất Việt Nam, nằm ở biên giới Việt - Trung, mang vẻ đẹp hùng vĩ và hoang sơ.', location_id: 'l008', contact: '0236 3572 234', opening_hours: '07:00-18:00', rating: 4.7, img_url: 'https://i.imgur.com/KZMQ6GK.jpg' },
        { attraction_id: 'a003', attraction_name: 'Phú Quốc', description: 'Phú Quốc là hòn đảo nổi tiếng với những bãi biển tuyệt đẹp, cùng các khu nghỉ dưỡng cao cấp và là thiên đường du lịch của Việt Nam.', location_id: 'l007', contact: '028 3829 2131', opening_hours: '06:00-22:00', rating: 4.2, img_url: 'https://i.imgur.com/0Bi7m7K.jpg' },
        { attraction_id: 'a004', attraction_name: 'Hội An', description: 'Thành phố cổ Hội An nổi tiếng với những con phố cổ kính và kiến trúc độc đáo, là di sản văn hóa thế giới.', location_id: 'l006', contact: '0235 3910 200', opening_hours: '08:00-22:00', rating: 4.7, img_url: 'https://i.imgur.com/fTkJVPB.jpg' },
        { attraction_id: 'a005', attraction_name: 'Đà Lạt', description: 'Đà Lạt nổi tiếng với khí hậu mát mẻ, những hồ nước trong xanh, các khu vườn hoa và cảnh đẹp như Đồi Chè Cầu Đất, Thung Lũng Tình Yêu.', location_id: 'l005', contact: '0263 3837 383', opening_hours: '06:00-21:00', rating: 4.7, img_url: 'https://i.imgur.com/fjA14vo.jpg' },
        { attraction_id: 'a006', attraction_name: 'Phó Bảng', description: 'Phó Bảng là một ngôi làng cổ, nổi bật với kiến trúc nhà truyền thống của người H’mong, rất thích hợp cho những ai yêu thích khám phá văn hóa.', location_id: 'l009', contact: '0219 3792 015', opening_hours: '08:00-17:00', rating: 4.4, img_url: 'https://i.imgur.com/DblWOIA.jpg' },
        { attraction_id: 'a007', attraction_name: 'Công viên giải trí Sun World', description: 'Sun World là một trong những công viên giải trí lớn nhất Việt Nam, với nhiều trò chơi thú vị cho mọi lứa tuổi.', location_id: 'l002', contact: '028 3829 0707', opening_hours: '09:00-22:00', rating: 4.5, img_url: 'https://i.imgur.com/ytrKgQT.jpg' },
        { attraction_id: 'a008', attraction_name: 'Chợ Bến Thành', description: 'Chợ Bến Thành là một trong những khu chợ nổi tiếng nhất ở Hồ Chí Minh, nơi bạn có thể tìm thấy các món ăn đặc sản và đồ thủ công.', location_id: 'l002', contact: '028 3829 2121', opening_hours: '06:00-22:00', rating: 4.3, img_url: 'https://i.imgur.com/nocziid.jpg' },
        { attraction_id: 'a009', attraction_name: 'Chùa Một Cột', description: 'Chùa Một Cột ở Hà Nội là một trong những biểu tượng nổi tiếng của thủ đô, mang đậm nét kiến trúc Phật giáo.', location_id: 'l001', contact: '024 3822 0413', opening_hours: '08:00-18:00', rating: 4.6, img_url: 'https://i.imgur.com/H6miha1.jpg' },
        { attraction_id: 'a010', attraction_name: 'Khu di tích Mỹ Sơn', description: 'Mỹ Sơn là một khu di tích Chăm Pa nổi tiếng, được UNESCO công nhận là di sản văn hóa thế giới.', location_id: 'l006', contact: '0235 3652 349', opening_hours: '07:00-18:00', rating: 4.4, img_url: 'https://i.imgur.com/QkS0QXu.jpg' },
        { attraction_id: 'a011', attraction_name: 'Chợ Đồng Xuân', description: 'Chợ Đồng Xuân ở Hà Nội là một trong những khu chợ lâu đời, nơi bạn có thể mua sắm các sản phẩm thủ công truyền thống.', location_id: 'l001', contact: '024 3923 7689', opening_hours: '06:00-19:00', rating: 4.2, img_url: 'https://i.imgur.com/bxetz7p.jpg' },
        { attraction_id: 'a012', attraction_name: 'Tháp Rùa', description: 'Tháp Rùa là biểu tượng nổi tiếng của Hồ Gươm, gắn liền với lịch sử và văn hóa thủ đô Hà Nội.', location_id: 'l001', contact: '024 3826 7121', opening_hours: '06:00-22:00', rating: 4.5, img_url: 'https://i.imgur.com/cV1f9z3.jpg' },
        { attraction_id: 'a013', attraction_name: 'Vinpearl Land', description: 'Vinpearl Land là công viên giải trí và khu nghỉ dưỡng nổi tiếng ở Nha Trang, với các trò chơi cảm giác mạnh và bãi biển tuyệt đẹp.', location_id: 'l003', contact: '0258 3520 868', opening_hours: '09:00-21:00', rating: 4.7, img_url: 'https://i.imgur.com/05w2Ttm.jpg' },
        { attraction_id: 'a014', attraction_name: 'Vườn quốc gia Phong Nha-Kẻ Bàng', description: 'Phong Nha-Kẻ Bàng là một trong những khu vườn quốc gia nổi tiếng với các hang động kỳ vĩ, được UNESCO công nhận là di sản thiên nhiên thế giới.', location_id: 'l004', contact: '0232 3880 256', opening_hours: '07:00-17:00', rating: 4.8, img_url: 'https://i.imgur.com/ESUX5At.jpg' },
        { attraction_id: 'a015', attraction_name: 'Khu du lịch Suối Tiên', description: 'Suối Tiên là một khu du lịch sinh thái nổi tiếng ở Hồ Chí Minh, với nhiều hoạt động vui chơi giải trí và thư giãn.', location_id: 'l002', contact: '028 3898 8888', opening_hours: '08:00-18:00', rating: 4.4, img_url: 'https://i.imgur.com/vkX9Yxm.jpg' },
        { attraction_id: 'a016', attraction_name: 'Vườn hoa Mộc Lan', description: 'Vườn hoa Mộc Lan ở Đà Lạt là nơi lý tưởng để du khách thưởng thức các loại hoa, đặc biệt là vào mùa xuân.', location_id: 'l010', contact: '0263 3889 456', opening_hours: '07:00-17:00', rating: 4.3, img_url: 'https://i.imgur.com/U4s1dij.jpg' }
    ]);
};

exports.down = async function (knex) {
    return await knex('attractions').whereIn('attraction_id', [
        'a001', 'a002', 'a003', 'a004', 'a005', 'a006', 'a007', 'a008', 'a009', 'a010',
        'a011', 'a012', 'a013', 'a014', 'a015', 'a016'
    ]).del();
};
